### ISSUE TITLE
Password manager app hung

### ISSUE THREAD

**Issue by cybercrypto** [LedgerHQ/blue-app-password-manager#12]
Hi,
After upgrading to the latest firmware 1.4.1 the password manager app is now broken.
When opening the password manager app it will freeze/hung instantly.

**Comment by jhoff80** [comment]
Same here as well.

**Comment by riordant** [comment]
Can report that the password manager is working as normal for me as of 1.4.1

**Comment by btchip** [comment]
Yes, it was updated to work in 1.4.1 - if you have an old version, delete it from Ledger Manager then install it again
