### ISSUE TITLE
Passwords containing dots "."

### ISSUE THREAD

**Issue by tbergeron** [LedgerHQ/blue-app-password-manager#4]
Hi!

A few of my passwords contain dots "like.this.format" I don't seem to find a dot in the custom keyboard while inputting my passwords. Any idea?

Also any idea if there will be a UI to edit / sync passwords in the future?

Really love my Ledger Nano S so far! Great job! Thanks

**Comment by parkerhoyes** [comment]
I assume you mean you'd like to type a dot in the name for your password - you can do this by selecting the "@" character in the binary keyboard, which brings up a menu to type in a whole bunch of symbols.

**Comment by tbergeron** [comment]
Oh I see, I haven't tested it much yet. I guess I hadn't fully understood the concept of the module.

Just noticed it was only for the name and the password gets automatically generated! Do you know if we'll ever be able to use our own inserted passwords? 

Or at least it would be great to have a words password generator option so we could remember that password from heart in case we haven't our Ledger close.

Thanks for the tips, I found the dot character now!

**Comment by parkerhoyes** [comment]
No problem :)

Indeed, the password manager app is currently designed so that even if the device is lost, destroyed, or erased all you need is your master seed to recover your passwords, since all passwords are deterministically generated using your seed and the password's name.

As for human-readable passwords or custom passwords, that's a feature that @btchip will have to consider.

The binary keyboard is still rather new and if you have any feedback or suggestions on how to make it more user-friendly I'd be happy to accept feedback on the [BUI issues page](https://github.com/parkerhoyes/bolos-user-interface/issues).

**Comment by tbergeron** [comment]
I understand. I must say, there's quite a bit of ingenuity behind these little devices!

I was wondering about the "everything can be restored from your master seed". I read that everywhere but fail to understand how it works behind the scenes. So the master seed will really restore all wallets, configured U2F, passwords, etc. Right? So no worries about losing anything while upgrading firmware? 

How does that part work? I mean, there's nothing synced anywhere, how does the data get recovered on a new device? I guess it's akin to the bitcoin wallet restoration process but you guys seem to restore so much data from that mnemonic. At this point, it's magic for me hehe 😆 

After a second look, that binary keyboard rocks. Based on the screen size, it's incredible that we have access to pretty much all the keyboard. It got me a while to figure out how to work with it (left & right way of picking letters) but I believe anybody who will order that kind of device will be resourceful enough to figure it out after a few seconds. I starred that repo, I'm so glad everything is on GitHub! I'll sure provide feedback if I ever something could be improved 👍 

Sorry for the out of topic questions, just received my device and I'm pretty excited about it! Thanks again!

**Comment by parkerhoyes** [comment]
Glad you're excited about the device; it's interesting how platforms with limited resources often spark innovation 😃

The magic behind being able to generate so much from a master seed comes from the design of hierarchical deterministic key generation. As an input you use the master seed and a derivation path, and you get an application or wallet-specific key. There's more information about the technique [here](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki). It's important to remember that the device can't actually restore anything that the user types in after the seed, such as password names or U2F account counters, which would all need to be backed up, unless you can remember them - all other wallet data gets "backed up" in the blockchain.

If you have any other questions I'm sure there will be people on [the subreddit](https://www.reddit.com/r/ledgerwallet/) who will be happy to help, or the [developer Slack](http://slack.ledger.co/) to get a more direct route to the developers.

**Comment by tbergeron** [comment]
Very interesting! Thanks for the explanation, I'll sure go read more about how the blockchain works it is such an interesting piece of tech!

I'll sure join the subreddit and slack chat to ask more questions :) Thanks again for replying!
